package com.readingmusic.app.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 tonal palette — calm reading focus (teal primary)
val md_theme_light_primary = Color(0xFF006A60)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF9FF2E4)
val md_theme_light_onPrimaryContainer = Color(0xFF00201C)
val md_theme_light_secondary = Color(0xFF4A635F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E2)
val md_theme_light_onSecondaryContainer = Color(0xFF05201C)
val md_theme_light_tertiary = Color(0xFF456179)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCCE5FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E31)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5FBF8)
val md_theme_light_onBackground = Color(0xFF171D1B)
val md_theme_light_surface = Color(0xFFF5FBF8)
val md_theme_light_onSurface = Color(0xFF171D1B)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E1)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7976)
val md_theme_light_outlineVariant = Color(0xFFBEC9C5)
val md_theme_light_inverseSurface = Color(0xFF2B3230)
val md_theme_light_inverseOnSurface = Color(0xFFECF2EF)
val md_theme_light_inversePrimary = Color(0xFF83D5C8)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFEFF5F2)
val md_theme_light_surfaceContainer = Color(0xFFE9EFEC)
val md_theme_light_surfaceContainerHigh = Color(0xFFE3E9E6)
val md_theme_light_surfaceContainerHighest = Color(0xFFDEE4E1)
